	
		<footer>
			<p> ***************************************************************** <br>
				<?php echo $page_title;?> &nbsp Assignment: <?php echo $assignment_number;?> &nbsp Instructor: <?php echo $instructor_name;?> &nbsp Date: <?php echo $date;?> <br>
				*****************************************************************
			</p>
			<p> Author: Arthur (Alex) Maschio <br>
				Github: <a href="http://github.com/alexintp/itc240-2014" target="_blank"> alexintp/itc240-2014</a> <br>
				Contact information: <a href="mailto:amasch02@seattlecentral.edu"> amasch02@seattlecentral.edu</a> 
			</p>
		
	
		</footer>

	</body>
	
</html>


